-- =====================================================================
-- Every task comes from the Library. No exceptions.
-- Run once in Supabase -> SQL Editor, after referential-integrity.sql.
--
-- referential-integrity.sql made a task unable to outlive its resource,
-- but still allowed "ad-hoc" tasks with resource_id = null — tasks that
-- exist in someone's queue with nothing in the Library behind them. That
-- is the same inconsistency in a different shape: they can't be found,
-- reassigned, renamed or deleted from the Library, because as far as the
-- Library is concerned they don't exist.
--
-- This migration removes that escape hatch. resource_id becomes NOT NULL,
-- so "a task that isn't in the Library" is no longer representable.
--
-- Existing ad-hoc rows are adopted rather than deleted: each one gets the
-- Library resource it should always have had. The only rows dropped are
-- leftovers from the removed markShipped feature, which no code creates
-- any more.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Drop the "Apply what you learned: …" rows. These were generated by
--    a feature that no longer exists (see the note at the end of
--    app/actions.ts), duplicate each other, and describe no real work.
--    Their comments go with them.
-- ---------------------------------------------------------------------
delete from tasks
where resource_id is null
  and title like 'Apply what you learned:%';

-- ---------------------------------------------------------------------
-- 2. Homes for the work that was never filed.
-- ---------------------------------------------------------------------
insert into folders (name)
select 'Paid ads' where not exists (select 1 from folders where name = 'Paid ads');

insert into folders (name)
select 'Brand & copy' where not exists (select 1 from folders where name = 'Brand & copy');

-- ---------------------------------------------------------------------
-- 3. Give every remaining ad-hoc task a Library resource. The resource
--    takes the task's own type, so adopting it changes nothing the team
--    sees — the item simply becomes findable in the Library.
-- ---------------------------------------------------------------------
with mapping (title, folder) as (values
  ('Advanced Meta Ads course', 'Paid ads'),
  ('Audience research',        'Paid ads'),
  ('Creative hooks',           'Paid ads'),
  ('Meta Ads test campaign',   'Paid ads'),
  ('First test ad set',        'Paid ads'),
  ('Positioning basics',       'Brand & copy'),
  ('Offer design',             'Brand & copy'),
  ('Landing page copy',        'Brand & copy'),
  ('Brand color theory',       'Brand & copy'),
  ('Lead magnet ideas',        'Brand & copy'),
  ('Email deliverability',     'Brand & copy'),
  ('SEO audit of our site',    'SEO'),
  ('On-page checklist',        'SEO')
)
insert into resources (folder_id, title, type)
select f.id, m.title, min(t.type::text)::item_type
from mapping m
join folders f on f.name = m.folder
join tasks   t on t.title = m.title and t.resource_id is null
where not exists (select 1 from resources r where r.title = m.title)
group by f.id, m.title;

-- Link them up. The sync trigger then fills in each task's folder_id from
-- its new resource, so Today's "group by folder" view works for them too.
update tasks t
set resource_id = r.id
from resources r
where t.resource_id is null
  and r.title = t.title;

-- ---------------------------------------------------------------------
-- 4. Refuse to finish if anything is still unadopted, rather than
--    failing halfway through with an opaque NOT NULL violation.
-- ---------------------------------------------------------------------
do $$
declare n int;
begin
  select count(*) into n from tasks where resource_id is null;
  if n > 0 then
    raise exception
      'aborting: % task(s) still have no library resource — add them to the mapping above', n;
  end if;
end $$;

alter table tasks alter column resource_id set not null;

-- ---------------------------------------------------------------------
-- 5. resource_id can no longer be null, so the branch that used to let it
--    through becomes an error instead. A task that cannot resolve its
--    resource is now always a failure, never a silent pass.
-- ---------------------------------------------------------------------
create or replace function tasks_sync_from_resource() returns trigger
language plpgsql as $$
declare r record;
begin
  -- BEFORE triggers run ahead of the NOT NULL check, so name this case here
  -- or it surfaces as a confusing "resource no longer exists".
  if new.resource_id is null then
    raise exception 'a task must reference a library resource'
      using errcode = 'not_null_violation';
  end if;

  select title, type, source, folder_id into r
  from resources where id = new.resource_id;

  if not found then
    -- Resource deleted underneath us. Fail with the code the app maps to a
    -- friendly message, rather than writing a task that points at nothing.
    raise exception 'library resource % no longer exists', new.resource_id
      using errcode = 'foreign_key_violation';
  end if;

  new.title     := r.title;
  new.type      := r.type;
  new.source    := r.source;
  new.folder_id := r.folder_id;
  return new;
end $$;

commit;
